# Insert your dbt profile config here
default:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default


      #optional
      # host: datavault-ingestion-spark-thrift    # docker
      host: host.docker.internal      # local
      port: 7079
      user: dbt
      threads: 3
      server_side_parameters:
        "spark.driver.memory": "4g"